### ISSUE TITLE
ImportError: No module named franz.openrdf.model.value

### ISSUE THREAD

**Issue by cardinal27513** [cburgmer/surf#2]
Is this a known issue or I did something wrong???

> > > store = surf.Store(reader = "sparql_protocol", endpoint = "http://dbpedia.org/sparql", default_graph = "http://dbpedia.org")
> > > Traceback (most recent call last):
> > >   File "<interactive input>", line 1, in <module>
> > >   File "C:\Python27\lib\site-packages\surf-1.1.4_r371-py2.7.egg\surf\store.py", line 72, in **init**
> > >     load_plugins()
> > >   File "C:\Python27\lib\site-packages\surf-1.1.4_r371-py2.7.egg\surf\plugin\manager.py", line 72, in load_plugins
> > >     **init_plugins(__readers**, **ENTRYPOINT_READER**)
> > >   File "C:\Python27\lib\site-packages\surf-1.1.4_r371-py2.7.egg\surf\plugin\manager.py", line 60, in **init_plugins
> > >     plugin_class = entrypoint.load()
> > >   File "C:\Python27\lib\site-packages\pkg_resources.py", line 1954, in load
> > >     entry = __import**(self.module_name, globals(),globals(), ['**name**'])
> > >   File "C:\Python27\lib\site-packages\surf.allegro_franz-0.2.2_r362-py2.7.egg\allegro_franz\reader.py", line 39, in <module>
> > >     from allegro_franz.util import toRdfLib
> > >   File "C:\Python27\lib\site-packages\surf.allegro_franz-0.2.2_r362-py2.7.egg\allegro_franz\util.py", line 38, in <module>
> > >     from franz.openrdf.model.value import URI as fURIRef
> > > ImportError: No module named franz.openrdf.model.value

**Comment by timrdf** [comment]
Was there a solution to this :-)

Franz' site doesn't have a prominent "here's how to install our stuff"...

Thanks!

**Comment by dataparadigms** [comment]
The following fixed it for me:

```
sudo easy_install allegrordf
```
